name: Maven Check

on:
  push:

jobs:
  maven-check:
    name: Maven Check

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: 'maven' # Maven cache
    - name: Execute Maven build
      run: |
        mvn --batch-mode package
